### ISSUE TITLE
Version_details dashboard has tile referencing fields not part of Version explore

### ISSUE THREAD

**Issue by seanlhiggins** [llooker/jira_block_fivetran#1]
In this LookML dashboard file - https://github.com/llooker/jira_block_fivetran/blob/master/version_details.dashboard.lookml
There's a tile referencing fields in `issue_extended` but that view is not joined into the Explore (`Version`) being referenced 

 ```
- title: Issues
    name: Issues
    model: jira_block
    explore: version
    type: table
    fields:
    - issue_extended.id
    - issue_extended.status_name
    - issue_extended.severity_name
    - issue_extended.issue_type_name
    - issue_extended.story_points
    sorts:
    - issue_extended.id
```

Explore: https://github.com/llooker/jira_block_fivetran/blob/master/jira_block.model.lkml
```
# Update based on how you are associating versions to
explore: version {
  join: issue_fix_version {
    type: left_outer
    relationship: one_to_many
    sql_on: ${version.id} = ${issue_fix_version.version_id} ;;
  }
  join: issue {
    type: left_outer
    relationship: one_to_one
    sql_on: ${issue_fix_version.issue_id} = ${issue.id} ;;
  }
}
```
This means in the Explore we get this error:
<img width="1075" alt="screen shot 2018-07-26 at 17 09 35" src="https://user-images.githubusercontent.com/25038700/43274285-b38a2530-90f6-11e8-81f5-4e70307f8773.png">
